### PR TITLE
Adding BLM blog post

### PR DESCRIPTION
**Pull request by agubler**
## Description

Add BLM donation post and fixing dojo deps by @SitePenTorreyRice 

### Code

This PR touches:

- [ ] Content
- [ ] Content Pipeline
- [ ] Frontend
- [ ] Infrastructure

### Tests

- [ ] Tests are included?

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-3s5qrrp24.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-kklyj401x.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-3kxdpjx1u.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-b9qhzmffk.now.sh

**Comment by agubler** [comment]
CI passed: https://travis-ci.org/github/dojo/site/builds/695102983 - merging

**Pull request merged**
