### PR TITLE
Simplify adding of reference guides

### PR DESCRIPTION
**Pull request by KaneFreeman**
## Description

- Simply adding reference guides by only having to add the data once to `constants.ts` instead of in 4 places.

### Code

This PR touches:

- [ ] Content
- [ ] Content Pipeline
- [x] Frontend
- [ ] Infrastructure

### Tests

- [x] Tests are included?

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to https://dojoio-20mn0jm3b.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to https://dojoio-ffc2i4u93.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to https://dojoio-e7x3fj23y.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to https://dojoio-3nxau34k1.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to https://dojoio-3w9u6ywnt.now.sh

**Comment by agubler** [comment]
@KaneFreeman This is pretty outdated, now we have a couple `Learn*` widgets that deal with all the reference guides.

**Pull request closed without merging**
