### PR TITLE
Upgrade to latest dojo versions

### PR DESCRIPTION
**Pull request by KaneFreeman**
## Description

- Update framework and cli-build-app to the latest versions.
- Update other dependencies.

#210 

### Code

This PR touches:

- [ ] Content
- [ ] Content Pipeline
- [x] Frontend
- [ ] Infrastructure

### Tests

- [ ] Tests are included?

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-k48xg60rz.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-bmxo0wv40.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-33aq8jqld.now.sh
* zh-next-dojo-io: https://zh-next-dojo-io-971sjlwwj.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-9ix1elnk7.now.sh
* zh-next-dojo-io: https://zh-next-dojo-io-2lq4mu6l9.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-9ifvm8s12.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-gtdexce2k.now.sh

**Comment by KaneFreeman** [comment]
Closing in favor of #215

**Pull request closed without merging**
