### PR TITLE
Multi-language support

### LINKED ISSUE #66: Multi-Language Support
- Need language selector with predefined list of languages
- Language string (en, zh, fr, etc) needs to be added to the URLs (URLs should be dynamically added to BTR over using the `.dojorc` file).
- The selected language should be passed to the blocks.

Relates to #53

### PR DESCRIPTION
**Pull request by KaneFreeman**
## Description

Multi-language support

Resolves #66 

**WIP - DO NOT MERGE**

### Code

This PR touches:

- [ ] Content
- [x] Content Pipeline
- [x] Frontend
- [ ] Infrastructure

### Tests

- [x] Tests are included?

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
- dojo.io - https://dojoio-huceugaua.now.sh
- zh-cn.dojo.io - https://zh-cndojoio-2fkj6bljo.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* test: https://dojo.io
* test2: https://dojo.io

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-gs7ryeq1s.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-dcnygg43i.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-2cd4aoe48.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-6y9cwag94.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-kh96mcolk.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-k0fobsxh9.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-g9e3wczq4.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-1ia0e4ie1.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-gasl8003o.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-p0rd9jdgi.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-c86qqrqo2.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-9vdo1p3sb.now.sh

**Comment by KaneFreeman** [comment]
Closing in favor of #181

**Pull request closed without merging**
