### PR TITLE
Add demo/sandbox dropdown for examples, refactor menus

### LINKED ISSUE #69: Enhanced Playground
Integrating a drop down that allows to select either from examples or some other sample code.

Continuation of #4

### PR DESCRIPTION
**Pull request by KaneFreeman**
## Description

- Add demo/sandbox dropdown for examples with both.
- Default to demo on examples.
- Refactor menus to handle sub menus in `left/right (side)` (Learn section) or `dropdown` (Playground) modes.

Resolves #69 

### Code

This PR touches:

- [ ] Content
- [ ] Content Pipeline
- [x] Frontend
- [ ] Infrastructure

### Tests

- [x] Tests are included?

#### Desktop
image
image
image
image
image

#### Tablet
image
image
image
image

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-h9y9gu7qc.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-pen8rxjla.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-k1mn4hra2.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-6x5tsihng.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-grqkerdrh.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-ofrjcpa3t.now.sh

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-poex5k3e8.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-m3cca41ew.now.sh

**Comment by agubler** [comment]
@KaneFreeman One thing I noticed it that the menu for the examples can't be clicked in the white space after the text in the menu item.
menu

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* dojo.io: https://dojoio-6yaw09dya.now.sh
* zh-cn.dojo.io: https://zh-cndojoio-qnun3f7it.now.sh

**Pull request merged**
