### PR TITLE
Add new reference guides for resources and custom elements

### PR DESCRIPTION
**Pull request by agubler**
## Description

Adds new reference guides for resources and custom elements.

### Code

This PR touches:

- [x] Content
- [ ] Content Pipeline
- [ ] Frontend
- [ ] Infrastructure

### Tests

- [ ] Tests are included?

### CODE REVIEW

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-ko1f2i0o8.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-mdjvi7di6.now.sh

**Comment by agubler** [comment]
@KaneFreeman Yeah it's not merged into master yet :D

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-ezr59prcl.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-hmosnb30h.now.sh

**Comment by agubler** [comment]
@KaneFreeman this should now work (the docs are merged in on framework master)

**Comment by dojo-site** [comment]
This pull request has been deployed to:
* next-dojo-io: https://next-dojo-io-av210zmz8.now.sh
* zh-cn-next-dojo-io: https://zh-cn-next-dojo-io-dauuse74x.now.sh

**Pull request merged**
